import { SelfEvaluation } from "@prisma/client";

export const selfEvaluations: SelfEvaluation[] = [
  {
    id: 1,
    userId: 1,
    cycleId: 1,
    ownershipMentalityGrade: 5,
    ownershipMentalityComment: "Excellent ownership mentality",
    learningAgilityGrade: 4,
    learningAgilityComment: "Good learning agility",
    resilienceAdversityGrade: 3,
    resilienceAdversityComment: "Average resilience",
    teamworkGrade: 5,
    teamworkComment: "Great team player",
    outOfTheBoxThinkingBehavioralGrade: 4,
    outOfTheBoxThinkingBehavioralComment: "Creative thinker",
    deliveringQualityGrade: 5,
    deliveringQualityComment: "High quality delivery",
    meetingDeadlinesGrade: 4,
    meetingDeadlinesComment: "Meets deadlines consistently",
    doingMoreWithLessGrade: 3,
    doingMoreWithLessComment: "Efficient with resources",
    outOfTheBoxThinkingExecutionGrade: 4,
    outOfTheBoxThinkingExecutionComment: "Innovative execution",

    lastUpdated: new Date(),
    isFinalized: false
},
{
    id: 2,
    userId: 2,
    cycleId: 1,
    ownershipMentalityGrade: 3,
    ownershipMentalityComment: "Good sense of ownership",
    learningAgilityGrade: 5,
    learningAgilityComment: "Very agile learner",
    resilienceAdversityGrade: 4,
    resilienceAdversityComment: "Handles adversity well",
    teamworkGrade: 3,
    teamworkComment: "Effective team member",
    outOfTheBoxThinkingBehavioralGrade: 3,
    outOfTheBoxThinkingBehavioralComment: "Moderate creative thinking",
    deliveringQualityGrade: 4,
    deliveringQualityComment: "Consistent quality",
    meetingDeadlinesGrade: 5,
    meetingDeadlinesComment: "Always meets deadlines",
    doingMoreWithLessGrade: 4,
    doingMoreWithLessComment: "Resourceful",
    outOfTheBoxThinkingExecutionGrade: 3,
    outOfTheBoxThinkingExecutionComment: "Creative execution",

    lastUpdated: new Date(),
    isFinalized: false
},
{
    id: 3,
    userId: 3,
    cycleId: 1,
    ownershipMentalityGrade: 4,
    ownershipMentalityComment: "Strong ownership mentality",
    learningAgilityGrade: 3,
    learningAgilityComment: "Learns quickly",
    resilienceAdversityGrade: 5,
    resilienceAdversityComment: "Highly resilient",
    teamworkGrade: 4,
    teamworkComment: "Collaborates well",
    outOfTheBoxThinkingBehavioralGrade: 4,
    outOfTheBoxThinkingBehavioralComment: "Innovative thinker",
    deliveringQualityGrade: 3,
    deliveringQualityComment: "Reliable quality",
    meetingDeadlinesGrade: 4,
    meetingDeadlinesComment: "Usually meets deadlines",
    doingMoreWithLessGrade: 5,
    doingMoreWithLessComment: "Highly efficient",
    outOfTheBoxThinkingExecutionGrade: 4,
    outOfTheBoxThinkingExecutionComment: "Executes creatively",

    lastUpdated: new Date(),
    isFinalized: false
},
{
    id: 4,
    userId: 4,
    cycleId: 1,
    ownershipMentalityGrade: 2,
    ownershipMentalityComment: "Needs improvement in ownership",
    learningAgilityGrade: 3,
    learningAgilityComment: "Good learning ability",
    resilienceAdversityGrade: 4,
    resilienceAdversityComment: "Resilient under pressure",
    teamworkGrade: 2,
    teamworkComment: "Needs to improve teamwork",
    outOfTheBoxThinkingBehavioralGrade: 5,
    outOfTheBoxThinkingBehavioralComment: "Highly creative",
    deliveringQualityGrade: 3,
    deliveringQualityComment: "Consistent delivery",
    meetingDeadlinesGrade: 5,
    meetingDeadlinesComment: "Excellent with deadlines",
    doingMoreWithLessGrade: 4,
    doingMoreWithLessComment: "Uses resources well",
    outOfTheBoxThinkingExecutionGrade: 3,
    outOfTheBoxThinkingExecutionComment: "Innovative approach",

    lastUpdated: new Date(),
    isFinalized: false
},
{
    id: 5,
    userId: 5,
    cycleId: 1,
    ownershipMentalityGrade: 3,
    ownershipMentalityComment: "Shows ownership",
    learningAgilityGrade: 2,
    learningAgilityComment: "Needs to improve learning agility",
    resilienceAdversityGrade: 5,
    resilienceAdversityComment: "Very resilient",
    teamworkGrade: 4,
    teamworkComment: "Works well in teams",
    outOfTheBoxThinkingBehavioralGrade: 3,
    outOfTheBoxThinkingBehavioralComment: "Moderately creative",
    deliveringQualityGrade: 5,
    deliveringQualityComment: "High quality standards",
    meetingDeadlinesGrade: 4,
    meetingDeadlinesComment: "Dependable with deadlines",
    doingMoreWithLessGrade: 5,
    doingMoreWithLessComment: "Very efficient",
    outOfTheBoxThinkingExecutionGrade: 3,
    outOfTheBoxThinkingExecutionComment: "Creative solutions",

    lastUpdated: new Date(),
    isFinalized: false
},
{
    id: 6,
    userId: 6,
    cycleId: 1,
    ownershipMentalityGrade: 4,
    ownershipMentalityComment: "Good ownership mentality",
    learningAgilityGrade: 5,
    learningAgilityComment: "Excellent learner",
    resilienceAdversityGrade: 3,
    resilienceAdversityComment: "Average resilience",
    teamworkGrade: 5,
    teamworkComment: "Great team player",
    outOfTheBoxThinkingBehavioralGrade: 4,
    outOfTheBoxThinkingBehavioralComment: "Creative thinker",
    deliveringQualityGrade: 4,
    deliveringQualityComment: "Consistent quality",
    meetingDeadlinesGrade: 3,
    meetingDeadlinesComment: "Usually meets deadlines",
    doingMoreWithLessGrade: 2,
    doingMoreWithLessComment: "Needs to improve efficiency",
    outOfTheBoxThinkingExecutionGrade: 5,
    outOfTheBoxThinkingExecutionComment: "Highly innovative execution",

    lastUpdated: new Date(),
    isFinalized: false
},
{
    id: 7,
    userId: 8,
    cycleId: 1,
    ownershipMentalityGrade: 3,
    ownershipMentalityComment: "Average ownership mentality",
    learningAgilityGrade: 4,
    learningAgilityComment: "Quick learner",
    resilienceAdversityGrade: 5,
    resilienceAdversityComment: "Very resilient",
    teamworkGrade: 3,
    teamworkComment: "Cooperates well",
    outOfTheBoxThinkingBehavioralGrade: 2,
    outOfTheBoxThinkingBehavioralComment: "Needs to be more creative",
    deliveringQualityGrade: 5,
    deliveringQualityComment: "High quality delivery",
    meetingDeadlinesGrade: 4,
    meetingDeadlinesComment: "Meets deadlines consistently",
    doingMoreWithLessGrade: 3,
    doingMoreWithLessComment: "Efficient with resources",
    outOfTheBoxThinkingExecutionGrade: 5,
    outOfTheBoxThinkingExecutionComment: "Highly innovative execution",

    lastUpdated: new Date(),
    isFinalized: false
},

{
  id: 8,
  userId: 1,
  cycleId: 2,
  ownershipMentalityGrade: 4,
  ownershipMentalityComment: "Strong sense of ownership",
  learningAgilityGrade: 5,
  learningAgilityComment: "Excellent learning agility",
  resilienceAdversityGrade: 4,
  resilienceAdversityComment: "Resilient under pressure",
  teamworkGrade: 5,
  teamworkComment: "Outstanding team player",
  outOfTheBoxThinkingBehavioralGrade: 3,
  outOfTheBoxThinkingBehavioralComment: "Moderately creative thinker",
  deliveringQualityGrade: 4,
  deliveringQualityComment: "Consistently high quality",
  meetingDeadlinesGrade: 3,
  meetingDeadlinesComment: "Meets most deadlines",
  doingMoreWithLessGrade: 5,
  doingMoreWithLessComment: "Highly efficient",
  outOfTheBoxThinkingExecutionGrade: 4,
  outOfTheBoxThinkingExecutionComment: "Creative execution",

  lastUpdated: new Date(),
  isFinalized: false
},
{
  id: 9,
  userId: 2,
  cycleId: 2,
  ownershipMentalityGrade: 5,
  ownershipMentalityComment: "Exceptional ownership",
  learningAgilityGrade: 3,
  learningAgilityComment: "Good learning agility",
  resilienceAdversityGrade: 5,
  resilienceAdversityComment: "Very resilient",
  teamworkGrade: 4,
  teamworkComment: "Strong team player",
  outOfTheBoxThinkingBehavioralGrade: 2,
  outOfTheBoxThinkingBehavioralComment: "Needs more creativity",
  deliveringQualityGrade: 4,
  deliveringQualityComment: "Delivers good quality",
  meetingDeadlinesGrade: 5,
  meetingDeadlinesComment: "Always meets deadlines",
  doingMoreWithLessGrade: 3,
  doingMoreWithLessComment: "Efficient but can improve",
  outOfTheBoxThinkingExecutionGrade: 5,
  outOfTheBoxThinkingExecutionComment: "Highly creative execution",

  lastUpdated: new Date(),
  isFinalized: false
},
{
  id: 10,
  userId: 3,
  cycleId: 2,
  ownershipMentalityGrade: 3,
  ownershipMentalityComment: "Good sense of ownership",
  learningAgilityGrade: 4,
  learningAgilityComment: "Learns quickly",
  resilienceAdversityGrade: 3,
  resilienceAdversityComment: "Average resilience",
  teamworkGrade: 5,
  teamworkComment: "Excellent teamwork",
  outOfTheBoxThinkingBehavioralGrade: 4,
  outOfTheBoxThinkingBehavioralComment: "Creative thinker",
  deliveringQualityGrade: 5,
  deliveringQualityComment: "Delivers high quality",
  meetingDeadlinesGrade: 4,
  meetingDeadlinesComment: "Consistently meets deadlines",
  doingMoreWithLessGrade: 2,
  doingMoreWithLessComment: "Could be more efficient",
  outOfTheBoxThinkingExecutionGrade: 3,
  outOfTheBoxThinkingExecutionComment: "Moderately innovative",

  lastUpdated: new Date(),
  isFinalized: false
},
{
  id: 11,
  userId: 4,
  cycleId: 2,
  ownershipMentalityGrade: 4,
  ownershipMentalityComment: "Strong ownership mentality",
  learningAgilityGrade: 2,
  learningAgilityComment: "Needs to improve learning agility",
  resilienceAdversityGrade: 5,
  resilienceAdversityComment: "Highly resilient",
  teamworkGrade: 3,
  teamworkComment: "Good team player",
  outOfTheBoxThinkingBehavioralGrade: 5,
  outOfTheBoxThinkingBehavioralComment: "Very creative thinker",
  deliveringQualityGrade: 4,
  deliveringQualityComment: "Reliable quality delivery",
  meetingDeadlinesGrade: 2,
  meetingDeadlinesComment: "Needs to meet deadlines more consistently",
  doingMoreWithLessGrade: 4,
  doingMoreWithLessComment: "Efficient use of resources",
  outOfTheBoxThinkingExecutionGrade: 3,
  outOfTheBoxThinkingExecutionComment: "Innovative in execution",

  lastUpdated: new Date(),
  isFinalized: false
},
{
  id: 12,
  userId: 5,
  cycleId: 2,
  ownershipMentalityGrade: 2,
  ownershipMentalityComment: "Needs to improve ownership mentality",
  learningAgilityGrade: 3,
  learningAgilityComment: "Good learning ability",
  resilienceAdversityGrade: 4,
  resilienceAdversityComment: "Resilient",
  teamworkGrade: 5,
  teamworkComment: "Excellent team player",
  outOfTheBoxThinkingBehavioralGrade: 3,
  outOfTheBoxThinkingBehavioralComment: "Moderately creative",
  deliveringQualityGrade: 5,
  deliveringQualityComment: "High quality standards",
  meetingDeadlinesGrade: 3,
  meetingDeadlinesComment: "Usually meets deadlines",
  doingMoreWithLessGrade: 4,
  doingMoreWithLessComment: "Efficient with resources",
  outOfTheBoxThinkingExecutionGrade: 2,
  outOfTheBoxThinkingExecutionComment: "Needs more innovative execution",

  lastUpdated: new Date(),
  isFinalized: false
},
{
  id: 13,
  userId: 6,
  cycleId: 2,
  ownershipMentalityGrade: 4,
  ownershipMentalityComment: "Good ownership mentality",
  learningAgilityGrade: 5,
  learningAgilityComment: "Very agile learner",
  resilienceAdversityGrade: 3,
  resilienceAdversityComment: "Average resilience",
  teamworkGrade: 4,
  teamworkComment: "Works well in teams",
  outOfTheBoxThinkingBehavioralGrade: 5,
  outOfTheBoxThinkingBehavioralComment: "Highly creative thinker",
  deliveringQualityGrade: 2,
  deliveringQualityComment: "Needs to improve quality",
  meetingDeadlinesGrade: 4,
  meetingDeadlinesComment: "Meets deadlines",
  doingMoreWithLessGrade: 3,
  doingMoreWithLessComment: "Efficient but can improve",
  outOfTheBoxThinkingExecutionGrade: 5,
  outOfTheBoxThinkingExecutionComment: "Innovative execution",

  lastUpdated: new Date(),
  isFinalized: false
},
  // Adicione mais autoavaliações conforme necessário
];
