import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

// This was automatically generated by initializing shadcn ui (npx shadcn-ui@latest init)
//
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
